spider mark.local -v -n 100 ASTROM_xxxx
spider mark.local -v -n 300 COCIRS_0xxx
spider mark.local -v -n 300 COCIRS_0xxx_v2
spider mark.local -v -n 300 COCIRS_0xxx_v3
spider mark.local -v -n 300 COCIRS_1xxx
spider mark.local -v -n 300 COCIRS_1xxx_v2
spider mark.local -v -n 300 COCIRS_1xxx_v3
spider mark.local -v -n 300 COCIRS_5xxx
spider mark.local -v -n 300 COCIRS_6xxx
spider mark.local -v -n 300 COISS_0xxx
spider mark.local -v -n 300 COISS_0xxx_v1
spider mark.local -v -n 300 COISS_0xxx_v2
spider mark.local -v -n 300 COISS_1xxx
spider mark.local -v -n 300 COISS_2xxx
spider mark.local -v -n 300 COISS_3xxx
spider mark.local -v -n 300 COISS_3xxx_v1
spider mark.local -v -n 300 COISS_3xxx_v2
spider mark.local -v -n 300 COISS_3xxx_v3
spider mark.local -v -n 100 CORSS_8xxx_lien_resolution
spider mark.local -v -n 300 COUVIS_0xxx
spider mark.local -v -n 100 COUVIS_8xxx_lien_resolution
spider mark.local -v -n 300 COVIMS_0xxx
spider mark.local -v -n 100 COVIMS_8xxx_lien_resolution
spider mark.local -v -n 100 EBROCC_xxxx
spider mark.local -v -n 300 GO_0xxx
spider mark.local -v -n 300 HSTIx_xxxx
spider mark.local -v -n 300 HSTIx_xxxx_v1.0
spider mark.local -v -n 300 HSTJx_xxxx
spider mark.local -v -n 300 HSTJx_xxxx_v1.0
spider mark.local -v -n 300 HSTJx_xxxx_v1.1
spider mark.local -v -n 300 HSTNx_xxxx
spider mark.local -v -n 300 HSTOx_xxxx
spider mark.local -v -n 300 HSTOx_xxxx_v1.0
spider mark.local -v -n 300 HSTUx_xxxx
spider mark.local -v -n 300 HSTUx_xxxx_v1.0
spider mark.local -v -n 100 NHSP_xxxx
spider mark.local -v -n 300 NHxxLO_xxxx
spider mark.local -v -n 300 NHxxLO_xxxx_v1
spider mark.local -v -n 300 NHxxLO_xxxx_v2
spider mark.local -v -n 300 NHxxLO_xxxx_v3
spider mark.local -v -n 300 NHxxMV_xxxx
spider mark.local -v -n 300 NHxxMV_xxxx_v1
spider mark.local -v -n 300 NHxxMV_xxxx_v2
spider mark.local -v -n 100 RES_xxxx_prelim
spider mark.local -v -n 300 RPX_xxxx
spider mark.local -v -n 300 VG_0xxx
spider mark.local -v -n 100 VG_20xx
spider mark.local -v -n 100 VG_28xx
spider mark.local -v -n 100 VG_28xx_peer_review
spider mark.local -v -n 100 VGIRIS_xxxx_peer_review
spider mark.local -v -n 300 VGISS_5xxx
spider mark.local -v -n 300 VGISS_6xxx
spider mark.local -v -n 300 VGISS_7xxx
spider mark.local -v -n 300 VGISS_8xxx
